export const countriesISO2 = [
  { iso2: "JP", nome: "Japan" },
  { iso2: "CY", nome: "Cyprus" },
  { iso2: "BJ", nome: "Benin" },
  { iso2: "UY", nome: "Uruguay" },
  { iso2: "AG", nome: "Antigua and Barbuda" },
  { iso2: "VN", nome: "Viet Nam" },
  { iso2: "CG", nome: "Congo" },
  { iso2: "TV", nome: "Tuvalu" },
  { iso2: "KN", nome: "Saint Kitts and Nevis" },
  { iso2: "AD", nome: "Andorra" },
  { iso2: "SB", nome: "Solomon Islands" },
  { iso2: "SV", nome: "El Salvador" },
  { iso2: "MX", nome: "Mexico" },
  { iso2: "BY", nome: "Belarus" },
  { iso2: "MW", nome: "Malawi" },
  { iso2: "GY", nome: "Guyana" },
  { iso2: "SR", nome: "Suriname" },
  { iso2: "VA", nome: "Holy See" },
  { iso2: "AT", nome: "Austria" },
  { iso2: "ER", nome: "Eritrea" },
  { iso2: "FJ", nome: "Fiji" },
  { iso2: "GA", nome: "Gabon" },
  { iso2: "ZM", nome: "Zambia" },
  { iso2: "GI", nome: "Gibraltar" },
  { iso2: "HK", nome: "Hong Kong" },
  { iso2: "DE", nome: "Germany" },
  { iso2: "FM", nome: "Micronesia (Federated States of)" },
  { iso2: "BH", nome: "Bahrain" },
  { iso2: "KR", nome: "Korea (Republic of)" },
  { iso2: "CV", nome: "Cabo Verde" },
  { iso2: "CU", nome: "Cuba" },
  { iso2: "IR", nome: "Iran (Islamic Republic of)" },
  { iso2: "QA", nome: "Qatar" },
  { iso2: "BY", nome: "Belarus" },
  { iso2: "GN", nome: "Guinea" },
  { iso2: "SL", nome: "Sierra Leone" },
  { iso2: "TJ", nome: "Tajikistan" },
  { iso2: "MK", nome: "North Macedonia" },
  { iso2: "KE", nome: "Kenya" },
  { iso2: "YE", nome: "Yemen" },
  { iso2: "WS", nome: "Samoa" },
  { iso2: "ZW", nome: "Zimbabwe" },
  { iso2: "QA", nome: "Qatar" },
  { iso2: "KN", nome: "Saint Kitts and Nevis" },
  { iso2: "TM", nome: "Turkmenistan" },
];
