export const countriesISO3 = [
  { iso3: "BLR", nome: "Belarus" },
  { iso3: "BRA", nome: "Brazil" },
  { iso3: "GRL", nome: "Greenland" },
  { iso3: "GGY", nome: "Guernsey" },
  { iso3: "HKG", nome: "Hong Kong" },
  { iso3: "IRL", nome: "Ireland" },
  { iso3: "JAM", nome: "Jamaica" },
  { iso3: "KHM", nome: "Cambodia" },
  { iso3: "KGZ", nome: "Kyrgyzstan" },
  { iso3: "KOR", nome: "Korea (Republic of)" },
  { iso3: "LIE", nome: "Liechtenstein" },
  { iso3: "LTU", nome: "Lithuania" },
  { iso3: "LUX", nome: "Luxembourg" },
  { iso3: "MAC", nome: "Macao" },
  { iso3: "MDV", nome: "Maldives" },
  { iso3: "MKD", nome: "North Macedonia" },
  { iso3: "MMR", nome: "Myanmar" },
  { iso3: "NLD", nome: "Netherlands" },
  { iso3: "NOR", nome: "Norway" },
  { iso3: "PAK", nome: "Pakistan" },
  { iso3: "PHL", nome: "Philippines" },
  { iso3: "PRT", nome: "Portugal" },
  { iso3: "PRY", nome: "Paraguay" },
  { iso3: "SAU", nome: "Saudi Arabia" },
  { iso3: "SGP", nome: "Singapore" },
  { iso3: "SLV", nome: "El Salvador" },
  { iso3: "SWE", nome: "Sweden" },
  { iso3: "SYC", nome: "Seychelles" },
  { iso3: "THA", nome: "Thailand" },
  { iso3: "TJK", nome: "Tajikistan" },
  { iso3: "TON", nome: "Tonga" },
  { iso3: "TUR", nome: "Turkey" },
  { iso3: "TUV", nome: "Tuvalu" },
  { iso3: "UGA", nome: "Uganda" },
  { iso3: "URY", nome: "Uruguay" },
  { iso3: "UZB", nome: "Uzbekistan" },
  { iso3: "VCT", nome: "Saint Vincent and the Grenadines" },
  { iso3: "VNM", nome: "Viet Nam" },
  { iso3: "VUT", nome: "Vanuatu" },
  { iso3: "WSM", nome: "Samoa" },
  { iso3: "ZAF", nome: "South Africa" },
  { iso3: "ZMB", nome: "Zambia" },
  { iso3: "ZWE", nome: "Zimbabwe" },
  { iso3: "KIR", nome: "Kiribati" },
  { iso3: "IMN", nome: "Isle of Man" },
  { iso3: "IRN", nome: "Iran (Islamic Republic of)" },
  { iso3: "ITA", nome: "Italy" },
];
