name: Run Tests

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4.1.3

    - name: Set up Node.js
      uses: actions/setup-node@v4.0.2

    - name: Install dependencies
      run: yarn

    - name: Run tests
      run: yarn test

    - name: Archive Test Report
      uses: actions/upload-artifact@v4 # Correção da versão
      with:
        name: test-report
        path: coverage/ # Adiciona caminho para o artefato

    - name: List Files
      run: ls -la

    - name: Publish test coverage report
      uses: EndBug/add-and-commit@v4
      with:
        add: docs
        force: true
        message: Add generated docs
      env:
        GITHUB_TOKEN: $



    
